### PR TITLE
Polished Frontend

### PR DESCRIPTION
**Pull request by PlatPlat48**
Note: The Dockerfile does say to checkout the demo_polish_frontend branch; When we’re about to merge, make sure to checkout the develop branch instead.

### CODE REVIEW

**Comment by smover** [comment]
I cannot find the docker_polish_frontend submodule inside the ChimpDriver folder. Did you forget to import the submodule?


Also, when running: `$ docker build -t chimpcheck .`:

```Sending build context to Docker daemon  13.82kB
Error response from daemon: Dockerfile parse error line 7: unknown instruction: &&
```

You miss the \ at the end of line 6.

**Comment by PlatPlat48** [comment]
Fixed the error with the Dockerfile. That should be the only error.
The "git checkout docker_polish_frontend" lines talk about the specific branch it's currently pulling. It should not be a submodule.

**Comment by smover** [comment]
The branch is called `demo_docker_frontend` and not `docker_polish_frontend`!

Just a tip: execute the docker build image (or any other test if you have tests cases in your program) next time you create a pull request. This was a dumb mistake that took me time to debug while it would have been immediate to solve for you.

**Comment by PlatPlat48** [comment]
Wait, no. The branch should be called docker_polish_frontend...

**Pull request merged**
